print("Salom Git!")
print("Men Gitni organayapman!")
print("Login branchdagi variant!")
print("Login funksiyasi ustida ishlayapman!") 
print("Masterdagi variant!")
print("GitHubdan kelgan qator!")
print("Clone orqali yozildi!") 
