print("Salom Git!")
print("Men Gitni organayapman!")
print("Login branchdagi variant!")
print("Login funksiyasi ustida ishlayapman!") 
print("Masterdagi variant!")
print("GitHubdan kelgan qator!")
print("Clone orqali yozildi!") 
print("Masterdagi yangi ozgarish") 
print("Rebase feature 1") 
print("rebase feature 2") 
print("Force push yajribasi") 
